### PR TITLE
Only require illuminate/support in development

### PR DESCRIPTION
**Pull request by hannesvdvreken**

### CODE REVIEW

**Comment by hannesvdvreken** [comment]
What are your thoughts on this PR, @aloha?

**Comment by aloha** [comment]
Is there something I don't know about this package and it not being required in prod for the Facade and Providers?

**Comment by hannesvdvreken** [comment]
Basically the idea is that people who will work on this package will have the Facade class and ServiceProvider class available for running tests and stuff, but when people install this package when they use laravel, they will already have illuminate/support installed. You don't want to version limit them to the illuminate support version you require. Little to nothing has changed since 4.0. 5.0 will be a little bit different but nothing you can solve it to be backwards compatible.

**Comment by aloha** [comment]
I see.  Great point.

**Pull request merged**
