### PR TITLE
Created manager class which has same interface, like proposed in #17

### PR DESCRIPTION
**Pull request by hannesvdvreken**
I'll refactor once #33 is merged in, because we could use the interface in the commands instead.

### CODE REVIEW

**Comment by hannesvdvreken** [comment]
When all 3 of these PR's are merged in I will kick off testing.

**Comment by aloha** [comment]
I'll have to resolve the conflicts when I get home from work.  Looks good tho.  Thanks!

**Comment by hannesvdvreken** [comment]
Nah, I will refactor it for you, since you agree with the intention.

**Comment by hannesvdvreken** [comment]
Refactor complete, can you review please?

**Pull request merged**
